---
title: "README"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
```


```{r}
drake::loadd(landings_clean)
```

```{r, message=FALSE}
trip_summary <- landings_clean %>%
  dplyr::group_by(trip_id) %>%
  dplyr::summarise(
    date = dplyr::first(date), 
    fisher = dplyr::first(fisher), 
    total_price = sum(total_price), 
    weight_kg = sum(weight_kg),
    n_species = dplyr::n_distinct(common_malay))

fisher_summary <- landings_clean %>%
  dplyr::group_by(fisher) %>%
  dplyr::summarise(
    imei = dplyr::first(imei),
    first_trip = min(date), 
    last_trip = max(date),
    total_price = sum(total_price), 
    weight_kg = sum(weight_kg),
    n_species = dplyr::n_distinct(common_malay))
```

Between `r format(min(trip_summary$date), "%d %B %Y")` and `r format(max(trip_summary$date), "%d %B %Y")` we recorded `r nrow(trip_summary)` trips by `r dplyr::n_distinct(landings_clean$fisher)` fishers. During this time, GPS trackers were installed in `r length(na.omit(fisher_summary$imei))` boats. 

```{r}
trip_summary %>%
  ggplot(aes(x = date)) +
  geom_histogram(binwidth = 14, boundary = as.Date("2020-01-01")) +
  theme_minimal()
```

```{r}
fisher_summary %>%
  dplyr::mutate(fisher = forcats::fct_reorder(fisher, first_trip, .desc = TRUE)) %>%
  ggplot(aes(y = fisher)) +
  geom_segment(aes(x = first_trip, 
                   xend = last_trip, yend = fisher, colour = is.na(imei))) +
  geom_point(data = trip_summary, 
             aes(x = date), size = 1, shape = 3) +
  theme_minimal()
```

```{r}
species_summary <- landings_clean %>%
  dplyr::filter(!is.na(price_kg)) %>%
  dplyr::mutate(species = forcats::fct_lump_n(common_malay, w = price_kg*weight_kg, n = 20)) %>%
  dplyr::group_by(species) %>%
  dplyr::summarise(
    frequency = dplyr::n_distinct(trip_id), 
    weight = sum(weight_kg, na.rm = TRUE), 
    price_kg = mean(price_kg, na.rm = TRUE)) %>%
  dplyr::mutate(species = forcats::fct_reorder(species, price_kg*weight), 
                species = forcats::fct_relevel(species, "Other"))

species_summary %>%
  ggplot(aes(x = species, y = price_kg*weight)) +
  geom_col() +
  coord_flip()

species_summary %>%
  ggplot(aes(x = species, y = price_kg)) +
  geom_col() +
  coord_flip()

species_summary %>%
  ggplot(aes(x = species, y = weight)) +
  geom_col() +
  coord_flip()
```

```{r}
trip_summary %>%
  ggplot(aes(x = date, y = weight_kg)) +
  geom_point(aes(colour = fisher))

trip_summary %>%
  ggplot(aes(x = date, y = total_price)) +
  geom_point(aes(colour = fisher))
```


